name: Close Pull Request

on:
  pull_request_target:
    types: [opened]

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: Anam020990/close-pull-request
      with:
        # Optional. Post a issue comment just before closing a pull request.
        comment: "We appreciate your contributions. However, please create PRs on your fork and not on the original project repository. Thank you!"
